default_stages: [ commit, manual ]

repos:
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

#  - repo: https://github.com/pycqa/flake8
#    rev: 6.1.0
#    hooks:
#      - id: flake8
#        args:
#          - --config=.code_quality/.flake8

  #  - repo: https://github.com/PyCQA/bandit
  #    rev: '' # Update me!
  #    hooks:
  #    - id: bandit
  #      args:
  #        - "--skip"
  #        - "B311"
  #        - "-x"
  #        - "test/**"
  #        - "--skip"
  #        - "B104"
  #        - "--skip"
  #        - "B311"


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --config-file=.code_quality/mypy.ini
        additional_dependencies:
          - types-PyMySQL
          - types-requests
          - types-cachetools
          - types-pyyaml
        language_version: python3.11